class SmtlibCapability:

    ### serialize constraints
    def to_smt2(self):
        res = []
        res.append("; generated by vega")
        res.append("(set-info :status unknown)")

        ### Collect sorts
        sorts = set()
        for v in self.variables.keys():
            sorts.add(v.sort)

        for sort in sorts: # TODO
            res.append("(declare-datatypes () (({} {})))".format(sort.name, ' '.join(["({})".format(x) for x in sort.values])))
            for v in sort.values:
                res.append("(declare-fun {} () {})".format(v.name, sort.name))

        for v in self.variables.keys():
            res.append("(declare-fun {} () {})".format(v.name, v.sort.name))
        
        for expr in self.constraints:
            res.append("(assert\n {})".format(expr.to_smt2()))

        res.append("(check-sat)")
        
        return '\n'.join(res)