# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install develop
      run: |
        python3 setup.py develop --user
    - name: Test solver
      run: |
        python3 tests/test.py
    - name: Test smtlib and command line
      run:
        ### Load smt and dump smt and use vega command
        - python3 tests/test_smtlib.py tests/test_smtlib_1.smt2 /tmp/test.smt2 && vega -smt2 /tmp/test.smt2
        ### Load and solve
        - vega -smt2 tests/test_smtlib_1.smt2
        - vega -smt2 tests/test_smtlib_2.smt2
      env:
        PATH: /home/runner/.local/bin:$PATH